# Generated by Django 3.2.8 on 2022-12-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
                ('home_address', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=12),
        ),
    ]
