# Generated by Django 3.2.8 on 2022-12-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221224_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_image', verbose_name='User Profile Image'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='home_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile_image', verbose_name='User Profile Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
