# Generated by Django 3.2.8 on 2022-12-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('accounts', '0006_auto_20221227_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_class', to='administration.studentclass'),
        ),
    ]
