# Generated by Django 3.2.8 on 2022-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
